// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMf52M3B8Js2ziDk8ovvCdOQEliBJr6_k',
    appId: '1:981096603142:web:c2f07806582c234f926d87',
    messagingSenderId: '981096603142',
    projectId: 'pesaplan-da74f',
    authDomain: 'pesaplan-da74f.firebaseapp.com',
    storageBucket: 'pesaplan-da74f.firebasestorage.app',
    measurementId: 'G-KRKS3PYQ3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByw6rfqNmaDF0B0VMhjiMlZ_vsKfUSHo4',
    appId: '1:981096603142:android:05216d0c4ecf7cad926d87',
    messagingSenderId: '981096603142',
    projectId: 'pesaplan-da74f',
    storageBucket: 'pesaplan-da74f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIpdB8EGWLGQcf2CmgKoTLNMAnoyo2wzU',
    appId: '1:981096603142:ios:b5a0697ab55b4ccf926d87',
    messagingSenderId: '981096603142',
    projectId: 'pesaplan-da74f',
    storageBucket: 'pesaplan-da74f.firebasestorage.app',
    iosBundleId: 'KelvinKimani.com.pesaplanNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIpdB8EGWLGQcf2CmgKoTLNMAnoyo2wzU',
    appId: '1:981096603142:ios:b5a0697ab55b4ccf926d87',
    messagingSenderId: '981096603142',
    projectId: 'pesaplan-da74f',
    storageBucket: 'pesaplan-da74f.firebasestorage.app',
    iosBundleId: 'KelvinKimani.com.pesaplanNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMf52M3B8Js2ziDk8ovvCdOQEliBJr6_k',
    appId: '1:981096603142:web:e3b50d4c83314da0926d87',
    messagingSenderId: '981096603142',
    projectId: 'pesaplan-da74f',
    authDomain: 'pesaplan-da74f.firebaseapp.com',
    storageBucket: 'pesaplan-da74f.firebasestorage.app',
    measurementId: 'G-D8RRFBDZLP',
  );
}
